{% set name = "pandavro" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f8486d908916092071a63dbee2bc324a8f2a1af1a6ed493d74dc6ef700a01a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - fastavro >=0.14.11
    - numpy >=1.7.0
    - pandas >=1.1.5
    - six >=1.9

test:
  imports:
    - pandavro

about:
  home: https://github.com/ynqa/pandavro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The interface between Avro and pandas DataFrame
  doc_url: https://github.com/ynqa/pandavro/blob/master/README.md
  dev_url: https://github.com/ynqa/pandavro

extra:
  recipe-maintainers:
    - rabbit72
